version: '3.8'

services:
  ai-animation:
    build: .
    ports:
      - "${HOST_PORT:-8000}:8000"
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./.generated_html:/app/.generated_html
      - ./.recordings:/app/.recordings
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - TZ=Asia/Shanghai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
